#############################
# Site Defaults
#############################

title: Project Network - EAL ITET 2016
#email: your-email@domain.com
description: Documentation and configuration files for Project Network by Group7 at EAL ITET2016
baseurl: "" # the subpath of your site, e.g. /blog

# Using a valid but unregistered TLD - We use internal network DNS to route
# all traffic to it.
url: http://network.tools

#############################
# Build Settings
#############################
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
